/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEmergencyAccess, IEmergencyAccessInterface } from "../../interfaces/IEmergencyAccess.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "recordCount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "CustodianEmergencyKeysStored",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "doctor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "enum IEmergencyAccess.TriggerType",
        "name": "triggerType",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencyAccessTriggered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "trustedContacts",
        "type": "address[]"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "sessionDuration",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencyConfigured",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "newContacts",
        "type": "address[]"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencyContactsUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "recordCount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "contactCount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencyKeysStored",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "doctor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencyOTPConsumed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "doctor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "expiresAt",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencyOTPIssued",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "recordId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "doctor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencyRecordAccessed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencySessionExpired",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "EmergencySessionRevoked",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address[]",
        "name": "_trustedContacts",
        "type": "address[]"
      },
      {
        "internalType": "uint256",
        "name": "_sessionDuration",
        "type": "uint256"
      }
    ],
    "name": "configureEmergencyAccess",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_sessionId",
        "type": "uint256"
      }
    ],
    "name": "consumeEmergencyAccess",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "encryptedData",
        "type": "bytes"
      },
      {
        "internalType": "uint256[]",
        "name": "recordIds",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "patient",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "recordId",
        "type": "uint256"
      }
    ],
    "name": "getCustodianEmergencyKey",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      }
    ],
    "name": "getEmergencyConfig",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "patient",
            "type": "address"
          },
          {
            "internalType": "address[]",
            "name": "trustedContacts",
            "type": "address[]"
          },
          {
            "internalType": "uint256",
            "name": "sessionDuration",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "isConfigured",
            "type": "bool"
          }
        ],
        "internalType": "struct IEmergencyAccess.EmergencyConfig",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_recordId",
        "type": "uint256"
      }
    ],
    "name": "getEmergencyKey",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "encryptedKey",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getPendingSessions",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "sessionId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "patient",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "doctor",
            "type": "address"
          },
          {
            "internalType": "enum IEmergencyAccess.SessionStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "enum IEmergencyAccess.TriggerType",
            "name": "triggerType",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "triggeredAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "activatedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "expiresAt",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "encryptedOTP",
            "type": "bytes"
          },
          {
            "internalType": "uint256",
            "name": "recordsAccessed",
            "type": "uint256"
          }
        ],
        "internalType": "struct IEmergencyAccess.EmergencySession[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_sessionId",
        "type": "uint256"
      }
    ],
    "name": "getSession",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "sessionId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "patient",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "doctor",
            "type": "address"
          },
          {
            "internalType": "enum IEmergencyAccess.SessionStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "enum IEmergencyAccess.TriggerType",
            "name": "triggerType",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "triggeredAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "activatedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "expiresAt",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "encryptedOTP",
            "type": "bytes"
          },
          {
            "internalType": "uint256",
            "name": "recordsAccessed",
            "type": "uint256"
          }
        ],
        "internalType": "struct IEmergencyAccess.EmergencySession",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getSessionCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_doctor",
        "type": "address"
      }
    ],
    "name": "getSessionsByDoctor",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "sessionId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "patient",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "doctor",
            "type": "address"
          },
          {
            "internalType": "enum IEmergencyAccess.SessionStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "enum IEmergencyAccess.TriggerType",
            "name": "triggerType",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "triggeredAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "activatedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "expiresAt",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "encryptedOTP",
            "type": "bytes"
          },
          {
            "internalType": "uint256",
            "name": "recordsAccessed",
            "type": "uint256"
          }
        ],
        "internalType": "struct IEmergencyAccess.EmergencySession[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      }
    ],
    "name": "getSessionsByPatient",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "sessionId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "patient",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "doctor",
            "type": "address"
          },
          {
            "internalType": "enum IEmergencyAccess.SessionStatus",
            "name": "status",
            "type": "uint8"
          },
          {
            "internalType": "enum IEmergencyAccess.TriggerType",
            "name": "triggerType",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "triggeredAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "activatedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "expiresAt",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "encryptedOTP",
            "type": "bytes"
          },
          {
            "internalType": "uint256",
            "name": "recordsAccessed",
            "type": "uint256"
          }
        ],
        "internalType": "struct IEmergencyAccess.EmergencySession[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_doctor",
        "type": "address"
      }
    ],
    "name": "hasActiveSession",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_doctor",
        "type": "address"
      }
    ],
    "name": "hasPendingSession",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_contact",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      }
    ],
    "name": "isEmergencyContact",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_sessionId",
        "type": "uint256"
      },
      {
        "internalType": "bytes",
        "name": "_encryptedOTP",
        "type": "bytes"
      },
      {
        "internalType": "uint256",
        "name": "_sessionDuration",
        "type": "uint256"
      }
    ],
    "name": "issueEmergencyOTP",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_sessionId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_recordId",
        "type": "uint256"
      }
    ],
    "name": "logEmergencyRecordAccess",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_sessionId",
        "type": "uint256"
      }
    ],
    "name": "rejectEmergencyRequest",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_sessionId",
        "type": "uint256"
      }
    ],
    "name": "revokeEmergencySession",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256[]",
        "name": "recordIds",
        "type": "uint256[]"
      },
      {
        "internalType": "bytes[]",
        "name": "wrappedKeys",
        "type": "bytes[]"
      }
    ],
    "name": "storeCustodianEmergencyKeys",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256[]",
        "name": "_recordIds",
        "type": "uint256[]"
      },
      {
        "internalType": "address[]",
        "name": "_contacts",
        "type": "address[]"
      },
      {
        "internalType": "bytes[]",
        "name": "_encryptedKeys",
        "type": "bytes[]"
      }
    ],
    "name": "storeEmergencyKeys",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_patient",
        "type": "address"
      }
    ],
    "name": "triggerEmergencyAccess",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "sessionId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address[]",
        "name": "_newContacts",
        "type": "address[]"
      }
    ],
    "name": "updateEmergencyContacts",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEmergencyAccess__factory {
    static readonly abi = _abi;
    static createInterface(): IEmergencyAccessInterface {
      return new Interface(_abi) as IEmergencyAccessInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEmergencyAccess {
      return new Contract(address, _abi, runner) as unknown as IEmergencyAccess;
    }
  }
  