/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRecordManager__factory } from './IRecordManager__factory.js';
export { IUserRegistry__factory } from './IUserRegistry__factory.js';