/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAccessControl__factory } from './IAccessControl__factory.js';
export { IEmergencyAccess__factory } from './IEmergencyAccess__factory.js';
export { IRecordManager__factory } from './IRecordManager__factory.js';
export { IUserRegistry__factory } from './IUserRegistry__factory.js';