/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IRecordManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRecordManager__factory>
getContractFactory(name: 'IUserRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUserRegistry__factory>
getContractFactory(name: 'RecordManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RecordManager__factory>
getContractFactory(name: 'UserRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UserRegistry__factory>

  getContractAt(name: 'IRecordManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRecordManager>
getContractAt(name: 'IUserRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUserRegistry>
getContractAt(name: 'RecordManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RecordManager>
getContractAt(name: 'UserRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UserRegistry>

  deployContract(name: 'IRecordManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRecordManager>
deployContract(name: 'IUserRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUserRegistry>
deployContract(name: 'RecordManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RecordManager>
deployContract(name: 'UserRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UserRegistry>

  deployContract(name: 'IRecordManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRecordManager>
deployContract(name: 'IUserRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUserRegistry>
deployContract(name: 'RecordManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RecordManager>
deployContract(name: 'UserRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UserRegistry>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  