/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from './interfaces/index.js';
export type { interfaces };
export type { RecordManager } from './RecordManager.js';
export type { UserRegistry } from './UserRegistry.js';
export * as factories from './factories/index.js';
export type { IRecordManager } from './interfaces/IRecordManager.js';
export { IRecordManager__factory } from './factories/interfaces/IRecordManager__factory.js';
export type { IUserRegistry } from './interfaces/IUserRegistry.js';
export { IUserRegistry__factory } from './factories/interfaces/IUserRegistry__factory.js';
export { RecordManager__factory } from './factories/RecordManager__factory.js';
export { UserRegistry__factory } from './factories/UserRegistry__factory.js';