/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IUserRegistry {
      
    export type DoctorProfileStruct = {name: string, licenseNumber: string, specialty: string, institution: string, registeredAt: BigNumberish}

    export type DoctorProfileStructOutput = [name: string, licenseNumber: string, specialty: string, institution: string, registeredAt: bigint] & {name: string, licenseNumber: string, specialty: string, institution: string, registeredAt: bigint }
  

    export type UserProfileStruct = {role: BigNumberish, isRegistered: boolean, encryptionPublicKey: BytesLike, registeredAt: BigNumberish}

    export type UserProfileStructOutput = [role: bigint, isRegistered: boolean, encryptionPublicKey: string, registeredAt: bigint] & {role: bigint, isRegistered: boolean, encryptionPublicKey: string, registeredAt: bigint }
  
    }

  export interface UserRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getDoctorProfile" | "getPublicKey" | "getUserProfile" | "getUserRole" | "isDoctorVerified" | "isRegistered" | "owner" | "pause" | "paused" | "registerAsDoctor" | "registerAsPatient" | "totalDoctors" | "totalUsers" | "unpause" | "updatePublicKey"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Paused" | "PublicKeyUpdated" | "Unpaused" | "UserRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'getDoctorProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPublicKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isDoctorVerified', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerAsDoctor', values: [string, string, string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'registerAsPatient', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalDoctors', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalUsers', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePublicKey', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getDoctorProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDoctorVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAsDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAsPatient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDoctors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePublicKey', data: BytesLike): Result;
  }

  
    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PublicKeyUpdatedEvent {
      export type InputTuple = [userAddress: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [userAddress: string, timestamp: bigint];
      export interface OutputObject {userAddress: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserRegisteredEvent {
      export type InputTuple = [userAddress: AddressLike, role: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [userAddress: string, role: bigint, timestamp: bigint];
      export interface OutputObject {userAddress: string, role: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface UserRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): UserRegistry;
    waitForDeployment(): Promise<this>;

    interface: UserRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getDoctorProfile: TypedContractMethod<
      [_doctor: AddressLike, ],
      [IUserRegistry.DoctorProfileStructOutput],
      'view'
    >
    

    
    getPublicKey: TypedContractMethod<
      [_user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getUserProfile: TypedContractMethod<
      [_user: AddressLike, ],
      [IUserRegistry.UserProfileStructOutput],
      'view'
    >
    

    
    getUserRole: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isDoctorVerified: TypedContractMethod<
      [_doctor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [_user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    registerAsDoctor: TypedContractMethod<
      [_name: string, _licenseNumber: string, _specialty: string, _institution: string, _encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerAsPatient: TypedContractMethod<
      [_encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalDoctors: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalUsers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updatePublicKey: TypedContractMethod<
      [_newPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getDoctorProfile'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [IUserRegistry.DoctorProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPublicKey'): TypedContractMethod<
      [_user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUserProfile'): TypedContractMethod<
      [_user: AddressLike, ],
      [IUserRegistry.UserProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getUserRole'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isDoctorVerified'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [_user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerAsDoctor'): TypedContractMethod<
      [_name: string, _licenseNumber: string, _specialty: string, _institution: string, _encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerAsPatient'): TypedContractMethod<
      [_encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalDoctors'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalUsers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePublicKey'): TypedContractMethod<
      [_newPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PublicKeyUpdated'): TypedContractEvent<PublicKeyUpdatedEvent.InputTuple, PublicKeyUpdatedEvent.OutputTuple, PublicKeyUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'UserRegistered'): TypedContractEvent<UserRegisteredEvent.InputTuple, UserRegisteredEvent.OutputTuple, UserRegisteredEvent.OutputObject>;

    filters: {
      
      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PublicKeyUpdated(address,uint256)': TypedContractEvent<PublicKeyUpdatedEvent.InputTuple, PublicKeyUpdatedEvent.OutputTuple, PublicKeyUpdatedEvent.OutputObject>;
      PublicKeyUpdated: TypedContractEvent<PublicKeyUpdatedEvent.InputTuple, PublicKeyUpdatedEvent.OutputTuple, PublicKeyUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'UserRegistered(address,uint8,uint256)': TypedContractEvent<UserRegisteredEvent.InputTuple, UserRegisteredEvent.OutputTuple, UserRegisteredEvent.OutputObject>;
      UserRegistered: TypedContractEvent<UserRegisteredEvent.InputTuple, UserRegisteredEvent.OutputTuple, UserRegisteredEvent.OutputObject>;
    
    };
  }