/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace RecordManager {
      
    export type HealthRecordStruct = {recordId: BigNumberish, owner: AddressLike, ipfsCID: string, contentHash: BytesLike, recordType: BigNumberish, status: BigNumberish}

    export type HealthRecordStructOutput = [recordId: bigint, owner: string, ipfsCID: string, contentHash: string, recordType: bigint, status: bigint] & {recordId: bigint, owner: string, ipfsCID: string, contentHash: string, recordType: bigint, status: bigint }
  
    }

  export interface RecordManagerInterface extends Interface {
    getFunction(nameOrSignature: "addRecord" | "getEncryptedKey" | "getMyRecords" | "getRecord" | "getRecordCount" | "getRecordsByOwner" | "isRecordActive" | "owner" | "pause" | "paused" | "totalRecords" | "unpause" | "userRegistry"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Paused" | "RecordAdded" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'addRecord', values: [string, BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getEncryptedKey', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMyRecords', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRecordCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRecordsByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRecordActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRecords', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'userRegistry', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEncryptedKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMyRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecordCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecordsByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRecordActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userRegistry', data: BytesLike): Result;
  }

  
    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordAddedEvent {
      export type InputTuple = [recordId: BigNumberish, owner: AddressLike, ipfsCID: string, recordType: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, owner: string, ipfsCID: string, recordType: bigint, timestamp: bigint];
      export interface OutputObject {recordId: bigint, owner: string, ipfsCID: string, recordType: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RecordManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): RecordManager;
    waitForDeployment(): Promise<this>;

    interface: RecordManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRecord: TypedContractMethod<
      [_ipfsCID: string, _contentHash: BytesLike, _recordType: BigNumberish, _encryptedKey: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    getEncryptedKey: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getMyRecords: TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >
    

    
    getRecord: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [RecordManager.HealthRecordStructOutput],
      'view'
    >
    

    
    getRecordCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRecordsByOwner: TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    isRecordActive: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    totalRecords: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    userRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRecord'): TypedContractMethod<
      [_ipfsCID: string, _contentHash: BytesLike, _recordType: BigNumberish, _encryptedKey: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEncryptedKey'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMyRecords'): TypedContractMethod<
      [],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [RecordManager.HealthRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRecordCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRecordsByOwner'): TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isRecordActive'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalRecords'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RecordAdded'): TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RecordAdded(uint256,address,string,uint256,uint256)': TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
      RecordAdded: TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }