/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IAccessControl {
      
    export type AccessRequestStruct = {requestId: BigNumberish, doctor: AddressLike, patient: AddressLike, recordIds: BigNumberish[], reason: string, status: BigNumberish, requestedAt: BigNumberish, respondedAt: BigNumberish}

    export type AccessRequestStructOutput = [requestId: bigint, doctor: string, patient: string, recordIds: bigint[], reason: string, status: bigint, requestedAt: bigint, respondedAt: bigint] & {requestId: bigint, doctor: string, patient: string, recordIds: bigint[], reason: string, status: bigint, requestedAt: bigint, respondedAt: bigint }
  

    export type PermissionStruct = {isActive: boolean, grantedBy: AddressLike, grantedTo: AddressLike, recordId: BigNumberish, grantedAt: BigNumberish, expiresAt: BigNumberish, revokedAt: BigNumberish}

    export type PermissionStructOutput = [isActive: boolean, grantedBy: string, grantedTo: string, recordId: bigint, grantedAt: bigint, expiresAt: bigint, revokedAt: bigint] & {isActive: boolean, grantedBy: string, grantedTo: string, recordId: bigint, grantedAt: bigint, expiresAt: bigint, revokedAt: bigint }
  
    }

  export interface IAccessControlInterface extends Interface {
    getFunction(nameOrSignature: "approveAccess" | "batchRevoke" | "checkAccess" | "getPendingRequests" | "getPermissionsByOwner" | "getPermissionsForRecord" | "getRequestCount" | "getRequestsByDoctor" | "getSharedRecords" | "grantAccess" | "logAccess" | "rejectAccess" | "requestAccess" | "revokeAccess" | "revokeAllAccess"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessGranted" | "AccessRequestRejected" | "AccessRequested" | "AccessRevoked" | "RecordAccessed"): EventFragment;

    encodeFunctionData(functionFragment: 'approveAccess', values: [BigNumberish, BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'batchRevoke', values: [BigNumberish[], AddressLike[]]): string;
encodeFunctionData(functionFragment: 'checkAccess', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPendingRequests', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPermissionsByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPermissionsForRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRequestCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRequestsByDoctor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSharedRecords', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantAccess', values: [BigNumberish, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'logAccess', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectAccess', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'requestAccess', values: [AddressLike, BigNumberish[], string]): string;
encodeFunctionData(functionFragment: 'revokeAccess', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeAllAccess', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approveAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchRevoke', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPermissionsByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPermissionsForRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequestCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequestsByDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSharedRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAllAccess', data: BytesLike): Result;
  }

  
    export namespace AccessGrantedEvent {
      export type InputTuple = [recordId: BigNumberish, patient: AddressLike, doctor: AddressLike, expiresAt: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, patient: string, doctor: string, expiresAt: bigint, timestamp: bigint];
      export interface OutputObject {recordId: bigint, patient: string, doctor: string, expiresAt: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRequestRejectedEvent {
      export type InputTuple = [requestId: BigNumberish, patient: AddressLike, doctor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [requestId: bigint, patient: string, doctor: string, timestamp: bigint];
      export interface OutputObject {requestId: bigint, patient: string, doctor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRequestedEvent {
      export type InputTuple = [requestId: BigNumberish, doctor: AddressLike, patient: AddressLike, recordIds: BigNumberish[], reason: string, timestamp: BigNumberish];
      export type OutputTuple = [requestId: bigint, doctor: string, patient: string, recordIds: bigint[], reason: string, timestamp: bigint];
      export interface OutputObject {requestId: bigint, doctor: string, patient: string, recordIds: bigint[], reason: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AccessRevokedEvent {
      export type InputTuple = [recordId: BigNumberish, patient: AddressLike, doctor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, patient: string, doctor: string, timestamp: bigint];
      export interface OutputObject {recordId: bigint, patient: string, doctor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordAccessedEvent {
      export type InputTuple = [recordId: BigNumberish, accessor: AddressLike, recordOwner: AddressLike, accessType: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, accessor: string, recordOwner: string, accessType: bigint, timestamp: bigint];
      export interface OutputObject {recordId: bigint, accessor: string, recordOwner: string, accessType: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IAccessControl extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAccessControl;
    waitForDeployment(): Promise<this>;

    interface: IAccessControlInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveAccess: TypedContractMethod<
      [_requestId: BigNumberish, _expiresAt: BigNumberish, _encryptedKeys: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    batchRevoke: TypedContractMethod<
      [_recordIds: BigNumberish[], _doctors: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    checkAccess: TypedContractMethod<
      [_doctor: AddressLike, _recordId: BigNumberish, ],
      [[boolean, string] & {hasAccess: boolean, encryptedKey: string }],
      'view'
    >
    

    
    getPendingRequests: TypedContractMethod<
      [_patient: AddressLike, ],
      [IAccessControl.AccessRequestStructOutput[]],
      'view'
    >
    

    
    getPermissionsByOwner: TypedContractMethod<
      [_patient: AddressLike, ],
      [IAccessControl.PermissionStructOutput[]],
      'view'
    >
    

    
    getPermissionsForRecord: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [IAccessControl.PermissionStructOutput[]],
      'view'
    >
    

    
    getRequestCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRequestsByDoctor: TypedContractMethod<
      [_doctor: AddressLike, ],
      [IAccessControl.AccessRequestStructOutput[]],
      'view'
    >
    

    
    getSharedRecords: TypedContractMethod<
      [_doctor: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    grantAccess: TypedContractMethod<
      [_recordId: BigNumberish, _doctor: AddressLike, _expiresAt: BigNumberish, _encryptedKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    logAccess: TypedContractMethod<
      [_recordId: BigNumberish, _accessType: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectAccess: TypedContractMethod<
      [_requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    requestAccess: TypedContractMethod<
      [_patient: AddressLike, _recordIds: BigNumberish[], _reason: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    revokeAccess: TypedContractMethod<
      [_recordId: BigNumberish, _doctor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeAllAccess: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveAccess'): TypedContractMethod<
      [_requestId: BigNumberish, _expiresAt: BigNumberish, _encryptedKeys: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'batchRevoke'): TypedContractMethod<
      [_recordIds: BigNumberish[], _doctors: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkAccess'): TypedContractMethod<
      [_doctor: AddressLike, _recordId: BigNumberish, ],
      [[boolean, string] & {hasAccess: boolean, encryptedKey: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingRequests'): TypedContractMethod<
      [_patient: AddressLike, ],
      [IAccessControl.AccessRequestStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPermissionsByOwner'): TypedContractMethod<
      [_patient: AddressLike, ],
      [IAccessControl.PermissionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPermissionsForRecord'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [IAccessControl.PermissionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRequestCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRequestsByDoctor'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [IAccessControl.AccessRequestStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSharedRecords'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'grantAccess'): TypedContractMethod<
      [_recordId: BigNumberish, _doctor: AddressLike, _expiresAt: BigNumberish, _encryptedKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'logAccess'): TypedContractMethod<
      [_recordId: BigNumberish, _accessType: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectAccess'): TypedContractMethod<
      [_requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestAccess'): TypedContractMethod<
      [_patient: AddressLike, _recordIds: BigNumberish[], _reason: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAccess'): TypedContractMethod<
      [_recordId: BigNumberish, _doctor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAllAccess'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AccessGranted'): TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
getEvent(key: 'AccessRequestRejected'): TypedContractEvent<AccessRequestRejectedEvent.InputTuple, AccessRequestRejectedEvent.OutputTuple, AccessRequestRejectedEvent.OutputObject>;
getEvent(key: 'AccessRequested'): TypedContractEvent<AccessRequestedEvent.InputTuple, AccessRequestedEvent.OutputTuple, AccessRequestedEvent.OutputObject>;
getEvent(key: 'AccessRevoked'): TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
getEvent(key: 'RecordAccessed'): TypedContractEvent<RecordAccessedEvent.InputTuple, RecordAccessedEvent.OutputTuple, RecordAccessedEvent.OutputObject>;

    filters: {
      
      'AccessGranted(uint256,address,address,uint256,uint256)': TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
      AccessGranted: TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
    

      'AccessRequestRejected(uint256,address,address,uint256)': TypedContractEvent<AccessRequestRejectedEvent.InputTuple, AccessRequestRejectedEvent.OutputTuple, AccessRequestRejectedEvent.OutputObject>;
      AccessRequestRejected: TypedContractEvent<AccessRequestRejectedEvent.InputTuple, AccessRequestRejectedEvent.OutputTuple, AccessRequestRejectedEvent.OutputObject>;
    

      'AccessRequested(uint256,address,address,uint256[],string,uint256)': TypedContractEvent<AccessRequestedEvent.InputTuple, AccessRequestedEvent.OutputTuple, AccessRequestedEvent.OutputObject>;
      AccessRequested: TypedContractEvent<AccessRequestedEvent.InputTuple, AccessRequestedEvent.OutputTuple, AccessRequestedEvent.OutputObject>;
    

      'AccessRevoked(uint256,address,address,uint256)': TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
      AccessRevoked: TypedContractEvent<AccessRevokedEvent.InputTuple, AccessRevokedEvent.OutputTuple, AccessRevokedEvent.OutputObject>;
    

      'RecordAccessed(uint256,address,address,uint8,uint256)': TypedContractEvent<RecordAccessedEvent.InputTuple, RecordAccessedEvent.OutputTuple, RecordAccessedEvent.OutputObject>;
      RecordAccessed: TypedContractEvent<RecordAccessedEvent.InputTuple, RecordAccessedEvent.OutputTuple, RecordAccessedEvent.OutputObject>;
    
    };
  }