/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IEmergencyAccess {
      
    export type EmergencyConfigStruct = {patient: AddressLike, trustedContacts: AddressLike[], sessionDuration: BigNumberish, isConfigured: boolean}

    export type EmergencyConfigStructOutput = [patient: string, trustedContacts: string[], sessionDuration: bigint, isConfigured: boolean] & {patient: string, trustedContacts: string[], sessionDuration: bigint, isConfigured: boolean }
  

    export type EmergencySessionStruct = {sessionId: BigNumberish, patient: AddressLike, doctor: AddressLike, status: BigNumberish, triggerType: BigNumberish, triggeredAt: BigNumberish, activatedAt: BigNumberish, expiresAt: BigNumberish, encryptedOTP: BytesLike, recordsAccessed: BigNumberish}

    export type EmergencySessionStructOutput = [sessionId: bigint, patient: string, doctor: string, status: bigint, triggerType: bigint, triggeredAt: bigint, activatedAt: bigint, expiresAt: bigint, encryptedOTP: string, recordsAccessed: bigint] & {sessionId: bigint, patient: string, doctor: string, status: bigint, triggerType: bigint, triggeredAt: bigint, activatedAt: bigint, expiresAt: bigint, encryptedOTP: string, recordsAccessed: bigint }
  
    }

  export interface IEmergencyAccessInterface extends Interface {
    getFunction(nameOrSignature: "configureEmergencyAccess" | "consumeEmergencyAccess" | "getEmergencyConfig" | "getEmergencyKey" | "getPendingSessions" | "getSession" | "getSessionCount" | "getSessionsByDoctor" | "getSessionsByPatient" | "hasActiveSession" | "hasPendingSession" | "isEmergencyContact" | "issueEmergencyOTP" | "logEmergencyRecordAccess" | "rejectEmergencyRequest" | "revokeEmergencySession" | "storeEmergencyKeys" | "triggerEmergencyAccess" | "updateEmergencyContacts"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EmergencyAccessTriggered" | "EmergencyConfigured" | "EmergencyContactsUpdated" | "EmergencyKeysStored" | "EmergencyOTPConsumed" | "EmergencyOTPIssued" | "EmergencyRecordAccessed" | "EmergencySessionExpired" | "EmergencySessionRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'configureEmergencyAccess', values: [AddressLike[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'consumeEmergencyAccess', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEmergencyConfig', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEmergencyKey', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPendingSessions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSession', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSessionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSessionsByDoctor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSessionsByPatient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasActiveSession', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasPendingSession', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isEmergencyContact', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'issueEmergencyOTP', values: [BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'logEmergencyRecordAccess', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectEmergencyRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeEmergencySession', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'storeEmergencyKeys', values: [BigNumberish[], AddressLike[], BytesLike[]]): string;
encodeFunctionData(functionFragment: 'triggerEmergencyAccess', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateEmergencyContacts', values: [AddressLike[]]): string;

    decodeFunctionResult(functionFragment: 'configureEmergencyAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consumeEmergencyAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEmergencyConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEmergencyKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingSessions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSession', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSessionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSessionsByDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSessionsByPatient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasActiveSession', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasPendingSession', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEmergencyContact', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueEmergencyOTP', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logEmergencyRecordAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectEmergencyRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeEmergencySession', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeEmergencyKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'triggerEmergencyAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateEmergencyContacts', data: BytesLike): Result;
  }

  
    export namespace EmergencyAccessTriggeredEvent {
      export type InputTuple = [sessionId: BigNumberish, patient: AddressLike, doctor: AddressLike, triggerType: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [sessionId: bigint, patient: string, doctor: string, triggerType: bigint, timestamp: bigint];
      export interface OutputObject {sessionId: bigint, patient: string, doctor: string, triggerType: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyConfiguredEvent {
      export type InputTuple = [patient: AddressLike, trustedContacts: AddressLike[], sessionDuration: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [patient: string, trustedContacts: string[], sessionDuration: bigint, timestamp: bigint];
      export interface OutputObject {patient: string, trustedContacts: string[], sessionDuration: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyContactsUpdatedEvent {
      export type InputTuple = [patient: AddressLike, newContacts: AddressLike[], timestamp: BigNumberish];
      export type OutputTuple = [patient: string, newContacts: string[], timestamp: bigint];
      export interface OutputObject {patient: string, newContacts: string[], timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyKeysStoredEvent {
      export type InputTuple = [patient: AddressLike, recordCount: BigNumberish, contactCount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [patient: string, recordCount: bigint, contactCount: bigint, timestamp: bigint];
      export interface OutputObject {patient: string, recordCount: bigint, contactCount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyOTPConsumedEvent {
      export type InputTuple = [sessionId: BigNumberish, doctor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [sessionId: bigint, doctor: string, timestamp: bigint];
      export interface OutputObject {sessionId: bigint, doctor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyOTPIssuedEvent {
      export type InputTuple = [sessionId: BigNumberish, patient: AddressLike, doctor: AddressLike, expiresAt: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [sessionId: bigint, patient: string, doctor: string, expiresAt: bigint, timestamp: bigint];
      export interface OutputObject {sessionId: bigint, patient: string, doctor: string, expiresAt: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyRecordAccessedEvent {
      export type InputTuple = [sessionId: BigNumberish, recordId: BigNumberish, doctor: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [sessionId: bigint, recordId: bigint, doctor: string, timestamp: bigint];
      export interface OutputObject {sessionId: bigint, recordId: bigint, doctor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencySessionExpiredEvent {
      export type InputTuple = [sessionId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [sessionId: bigint, timestamp: bigint];
      export interface OutputObject {sessionId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencySessionRevokedEvent {
      export type InputTuple = [sessionId: BigNumberish, patient: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [sessionId: bigint, patient: string, timestamp: bigint];
      export interface OutputObject {sessionId: bigint, patient: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IEmergencyAccess extends BaseContract {
    
    connect(runner?: ContractRunner | null): IEmergencyAccess;
    waitForDeployment(): Promise<this>;

    interface: IEmergencyAccessInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    configureEmergencyAccess: TypedContractMethod<
      [_trustedContacts: AddressLike[], _sessionDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    consumeEmergencyAccess: TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [[string, bigint[]] & {encryptedData: string, recordIds: bigint[] }],
      'nonpayable'
    >
    

    
    getEmergencyConfig: TypedContractMethod<
      [_patient: AddressLike, ],
      [IEmergencyAccess.EmergencyConfigStructOutput],
      'view'
    >
    

    
    getEmergencyKey: TypedContractMethod<
      [_patient: AddressLike, _recordId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getPendingSessions: TypedContractMethod<
      [],
      [IEmergencyAccess.EmergencySessionStructOutput[]],
      'view'
    >
    

    
    getSession: TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [IEmergencyAccess.EmergencySessionStructOutput],
      'view'
    >
    

    
    getSessionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getSessionsByDoctor: TypedContractMethod<
      [_doctor: AddressLike, ],
      [IEmergencyAccess.EmergencySessionStructOutput[]],
      'view'
    >
    

    
    getSessionsByPatient: TypedContractMethod<
      [_patient: AddressLike, ],
      [IEmergencyAccess.EmergencySessionStructOutput[]],
      'view'
    >
    

    
    hasActiveSession: TypedContractMethod<
      [_patient: AddressLike, _doctor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasPendingSession: TypedContractMethod<
      [_patient: AddressLike, _doctor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isEmergencyContact: TypedContractMethod<
      [_contact: AddressLike, _patient: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    issueEmergencyOTP: TypedContractMethod<
      [_sessionId: BigNumberish, _encryptedOTP: BytesLike, _sessionDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    logEmergencyRecordAccess: TypedContractMethod<
      [_sessionId: BigNumberish, _recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectEmergencyRequest: TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeEmergencySession: TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    storeEmergencyKeys: TypedContractMethod<
      [_recordIds: BigNumberish[], _contacts: AddressLike[], _encryptedKeys: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    triggerEmergencyAccess: TypedContractMethod<
      [_patient: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateEmergencyContacts: TypedContractMethod<
      [_newContacts: AddressLike[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'configureEmergencyAccess'): TypedContractMethod<
      [_trustedContacts: AddressLike[], _sessionDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'consumeEmergencyAccess'): TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [[string, bigint[]] & {encryptedData: string, recordIds: bigint[] }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEmergencyConfig'): TypedContractMethod<
      [_patient: AddressLike, ],
      [IEmergencyAccess.EmergencyConfigStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getEmergencyKey'): TypedContractMethod<
      [_patient: AddressLike, _recordId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingSessions'): TypedContractMethod<
      [],
      [IEmergencyAccess.EmergencySessionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSession'): TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [IEmergencyAccess.EmergencySessionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSessionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSessionsByDoctor'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [IEmergencyAccess.EmergencySessionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSessionsByPatient'): TypedContractMethod<
      [_patient: AddressLike, ],
      [IEmergencyAccess.EmergencySessionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasActiveSession'): TypedContractMethod<
      [_patient: AddressLike, _doctor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasPendingSession'): TypedContractMethod<
      [_patient: AddressLike, _doctor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isEmergencyContact'): TypedContractMethod<
      [_contact: AddressLike, _patient: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'issueEmergencyOTP'): TypedContractMethod<
      [_sessionId: BigNumberish, _encryptedOTP: BytesLike, _sessionDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'logEmergencyRecordAccess'): TypedContractMethod<
      [_sessionId: BigNumberish, _recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectEmergencyRequest'): TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeEmergencySession'): TypedContractMethod<
      [_sessionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'storeEmergencyKeys'): TypedContractMethod<
      [_recordIds: BigNumberish[], _contacts: AddressLike[], _encryptedKeys: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'triggerEmergencyAccess'): TypedContractMethod<
      [_patient: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateEmergencyContacts'): TypedContractMethod<
      [_newContacts: AddressLike[], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EmergencyAccessTriggered'): TypedContractEvent<EmergencyAccessTriggeredEvent.InputTuple, EmergencyAccessTriggeredEvent.OutputTuple, EmergencyAccessTriggeredEvent.OutputObject>;
getEvent(key: 'EmergencyConfigured'): TypedContractEvent<EmergencyConfiguredEvent.InputTuple, EmergencyConfiguredEvent.OutputTuple, EmergencyConfiguredEvent.OutputObject>;
getEvent(key: 'EmergencyContactsUpdated'): TypedContractEvent<EmergencyContactsUpdatedEvent.InputTuple, EmergencyContactsUpdatedEvent.OutputTuple, EmergencyContactsUpdatedEvent.OutputObject>;
getEvent(key: 'EmergencyKeysStored'): TypedContractEvent<EmergencyKeysStoredEvent.InputTuple, EmergencyKeysStoredEvent.OutputTuple, EmergencyKeysStoredEvent.OutputObject>;
getEvent(key: 'EmergencyOTPConsumed'): TypedContractEvent<EmergencyOTPConsumedEvent.InputTuple, EmergencyOTPConsumedEvent.OutputTuple, EmergencyOTPConsumedEvent.OutputObject>;
getEvent(key: 'EmergencyOTPIssued'): TypedContractEvent<EmergencyOTPIssuedEvent.InputTuple, EmergencyOTPIssuedEvent.OutputTuple, EmergencyOTPIssuedEvent.OutputObject>;
getEvent(key: 'EmergencyRecordAccessed'): TypedContractEvent<EmergencyRecordAccessedEvent.InputTuple, EmergencyRecordAccessedEvent.OutputTuple, EmergencyRecordAccessedEvent.OutputObject>;
getEvent(key: 'EmergencySessionExpired'): TypedContractEvent<EmergencySessionExpiredEvent.InputTuple, EmergencySessionExpiredEvent.OutputTuple, EmergencySessionExpiredEvent.OutputObject>;
getEvent(key: 'EmergencySessionRevoked'): TypedContractEvent<EmergencySessionRevokedEvent.InputTuple, EmergencySessionRevokedEvent.OutputTuple, EmergencySessionRevokedEvent.OutputObject>;

    filters: {
      
      'EmergencyAccessTriggered(uint256,address,address,uint8,uint256)': TypedContractEvent<EmergencyAccessTriggeredEvent.InputTuple, EmergencyAccessTriggeredEvent.OutputTuple, EmergencyAccessTriggeredEvent.OutputObject>;
      EmergencyAccessTriggered: TypedContractEvent<EmergencyAccessTriggeredEvent.InputTuple, EmergencyAccessTriggeredEvent.OutputTuple, EmergencyAccessTriggeredEvent.OutputObject>;
    

      'EmergencyConfigured(address,address[],uint256,uint256)': TypedContractEvent<EmergencyConfiguredEvent.InputTuple, EmergencyConfiguredEvent.OutputTuple, EmergencyConfiguredEvent.OutputObject>;
      EmergencyConfigured: TypedContractEvent<EmergencyConfiguredEvent.InputTuple, EmergencyConfiguredEvent.OutputTuple, EmergencyConfiguredEvent.OutputObject>;
    

      'EmergencyContactsUpdated(address,address[],uint256)': TypedContractEvent<EmergencyContactsUpdatedEvent.InputTuple, EmergencyContactsUpdatedEvent.OutputTuple, EmergencyContactsUpdatedEvent.OutputObject>;
      EmergencyContactsUpdated: TypedContractEvent<EmergencyContactsUpdatedEvent.InputTuple, EmergencyContactsUpdatedEvent.OutputTuple, EmergencyContactsUpdatedEvent.OutputObject>;
    

      'EmergencyKeysStored(address,uint256,uint256,uint256)': TypedContractEvent<EmergencyKeysStoredEvent.InputTuple, EmergencyKeysStoredEvent.OutputTuple, EmergencyKeysStoredEvent.OutputObject>;
      EmergencyKeysStored: TypedContractEvent<EmergencyKeysStoredEvent.InputTuple, EmergencyKeysStoredEvent.OutputTuple, EmergencyKeysStoredEvent.OutputObject>;
    

      'EmergencyOTPConsumed(uint256,address,uint256)': TypedContractEvent<EmergencyOTPConsumedEvent.InputTuple, EmergencyOTPConsumedEvent.OutputTuple, EmergencyOTPConsumedEvent.OutputObject>;
      EmergencyOTPConsumed: TypedContractEvent<EmergencyOTPConsumedEvent.InputTuple, EmergencyOTPConsumedEvent.OutputTuple, EmergencyOTPConsumedEvent.OutputObject>;
    

      'EmergencyOTPIssued(uint256,address,address,uint256,uint256)': TypedContractEvent<EmergencyOTPIssuedEvent.InputTuple, EmergencyOTPIssuedEvent.OutputTuple, EmergencyOTPIssuedEvent.OutputObject>;
      EmergencyOTPIssued: TypedContractEvent<EmergencyOTPIssuedEvent.InputTuple, EmergencyOTPIssuedEvent.OutputTuple, EmergencyOTPIssuedEvent.OutputObject>;
    

      'EmergencyRecordAccessed(uint256,uint256,address,uint256)': TypedContractEvent<EmergencyRecordAccessedEvent.InputTuple, EmergencyRecordAccessedEvent.OutputTuple, EmergencyRecordAccessedEvent.OutputObject>;
      EmergencyRecordAccessed: TypedContractEvent<EmergencyRecordAccessedEvent.InputTuple, EmergencyRecordAccessedEvent.OutputTuple, EmergencyRecordAccessedEvent.OutputObject>;
    

      'EmergencySessionExpired(uint256,uint256)': TypedContractEvent<EmergencySessionExpiredEvent.InputTuple, EmergencySessionExpiredEvent.OutputTuple, EmergencySessionExpiredEvent.OutputObject>;
      EmergencySessionExpired: TypedContractEvent<EmergencySessionExpiredEvent.InputTuple, EmergencySessionExpiredEvent.OutputTuple, EmergencySessionExpiredEvent.OutputObject>;
    

      'EmergencySessionRevoked(uint256,address,uint256)': TypedContractEvent<EmergencySessionRevokedEvent.InputTuple, EmergencySessionRevokedEvent.OutputTuple, EmergencySessionRevokedEvent.OutputObject>;
      EmergencySessionRevoked: TypedContractEvent<EmergencySessionRevokedEvent.InputTuple, EmergencySessionRevokedEvent.OutputTuple, EmergencySessionRevokedEvent.OutputObject>;
    
    };
  }