/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRecordManager } from './IRecordManager.js';
export type { IUserRegistry } from './IUserRegistry.js';