/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccessControl } from './IAccessControl.js';
export type { IEmergencyAccess } from './IEmergencyAccess.js';
export type { IRecordManager } from './IRecordManager.js';
export type { IUserRegistry } from './IUserRegistry.js';