/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IRecordManager {
      
    export type HealthRecordStruct = {recordId: BigNumberish, owner: AddressLike, ipfsCID: string, contentHash: BytesLike, recordType: BigNumberish, status: BigNumberish, isEmergency: boolean, createdAt: BigNumberish, updatedAt: BigNumberish}

    export type HealthRecordStructOutput = [recordId: bigint, owner: string, ipfsCID: string, contentHash: string, recordType: bigint, status: bigint, isEmergency: boolean, createdAt: bigint, updatedAt: bigint] & {recordId: bigint, owner: string, ipfsCID: string, contentHash: string, recordType: bigint, status: bigint, isEmergency: boolean, createdAt: bigint, updatedAt: bigint }
  
    }

  export interface IRecordManagerInterface extends Interface {
    getFunction(nameOrSignature: "addRecord" | "archiveRecord" | "deleteRecord" | "getContentHash" | "getEmergencyRecords" | "getEncryptedKey" | "getRecord" | "getRecordCID" | "getRecordCount" | "getRecordsByOwner" | "isRecordActive" | "removeEncryptedKey" | "restoreRecord" | "setEmergencyFlag" | "storeEncryptedKey"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EmergencyFlagUpdated" | "RecordAdded" | "RecordArchived" | "RecordDeleted" | "RecordRestored"): EventFragment;

    encodeFunctionData(functionFragment: 'addRecord', values: [string, BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'archiveRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deleteRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getContentHash', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEmergencyRecords', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEncryptedKey', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRecordCID', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRecordCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRecordsByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRecordActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeEncryptedKey', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'restoreRecord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setEmergencyFlag', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'storeEncryptedKey', values: [BigNumberish, AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'addRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'archiveRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deleteRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContentHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEmergencyRecords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEncryptedKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecordCID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecordCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecordsByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRecordActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeEncryptedKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'restoreRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEmergencyFlag', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'storeEncryptedKey', data: BytesLike): Result;
  }

  
    export namespace EmergencyFlagUpdatedEvent {
      export type InputTuple = [recordId: BigNumberish, owner: AddressLike, isEmergency: boolean, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, owner: string, isEmergency: boolean, timestamp: bigint];
      export interface OutputObject {recordId: bigint, owner: string, isEmergency: boolean, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordAddedEvent {
      export type InputTuple = [recordId: BigNumberish, owner: AddressLike, ipfsCID: string, recordType: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, owner: string, ipfsCID: string, recordType: bigint, timestamp: bigint];
      export interface OutputObject {recordId: bigint, owner: string, ipfsCID: string, recordType: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordArchivedEvent {
      export type InputTuple = [recordId: BigNumberish, owner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, owner: string, timestamp: bigint];
      export interface OutputObject {recordId: bigint, owner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordDeletedEvent {
      export type InputTuple = [recordId: BigNumberish, owner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, owner: string, timestamp: bigint];
      export interface OutputObject {recordId: bigint, owner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecordRestoredEvent {
      export type InputTuple = [recordId: BigNumberish, owner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [recordId: bigint, owner: string, timestamp: bigint];
      export interface OutputObject {recordId: bigint, owner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IRecordManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRecordManager;
    waitForDeployment(): Promise<this>;

    interface: IRecordManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRecord: TypedContractMethod<
      [_ipfsCID: string, _contentHash: BytesLike, _recordType: BigNumberish, _encryptedKey: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    archiveRecord: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deleteRecord: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getContentHash: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getEmergencyRecords: TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getEncryptedKey: TypedContractMethod<
      [_recordId: BigNumberish, _user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getRecord: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [IRecordManager.HealthRecordStructOutput],
      'view'
    >
    

    
    getRecordCID: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getRecordCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRecordsByOwner: TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    isRecordActive: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    removeEncryptedKey: TypedContractMethod<
      [_recordId: BigNumberish, _grantee: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    restoreRecord: TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setEmergencyFlag: TypedContractMethod<
      [_recordId: BigNumberish, _isEmergency: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    storeEncryptedKey: TypedContractMethod<
      [_recordId: BigNumberish, _grantee: AddressLike, _encryptedKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRecord'): TypedContractMethod<
      [_ipfsCID: string, _contentHash: BytesLike, _recordType: BigNumberish, _encryptedKey: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'archiveRecord'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deleteRecord'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getContentHash'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getEmergencyRecords'): TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getEncryptedKey'): TypedContractMethod<
      [_recordId: BigNumberish, _user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRecord'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [IRecordManager.HealthRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRecordCID'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRecordCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRecordsByOwner'): TypedContractMethod<
      [_owner: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isRecordActive'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removeEncryptedKey'): TypedContractMethod<
      [_recordId: BigNumberish, _grantee: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'restoreRecord'): TypedContractMethod<
      [_recordId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEmergencyFlag'): TypedContractMethod<
      [_recordId: BigNumberish, _isEmergency: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'storeEncryptedKey'): TypedContractMethod<
      [_recordId: BigNumberish, _grantee: AddressLike, _encryptedKey: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EmergencyFlagUpdated'): TypedContractEvent<EmergencyFlagUpdatedEvent.InputTuple, EmergencyFlagUpdatedEvent.OutputTuple, EmergencyFlagUpdatedEvent.OutputObject>;
getEvent(key: 'RecordAdded'): TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
getEvent(key: 'RecordArchived'): TypedContractEvent<RecordArchivedEvent.InputTuple, RecordArchivedEvent.OutputTuple, RecordArchivedEvent.OutputObject>;
getEvent(key: 'RecordDeleted'): TypedContractEvent<RecordDeletedEvent.InputTuple, RecordDeletedEvent.OutputTuple, RecordDeletedEvent.OutputObject>;
getEvent(key: 'RecordRestored'): TypedContractEvent<RecordRestoredEvent.InputTuple, RecordRestoredEvent.OutputTuple, RecordRestoredEvent.OutputObject>;

    filters: {
      
      'EmergencyFlagUpdated(uint256,address,bool,uint256)': TypedContractEvent<EmergencyFlagUpdatedEvent.InputTuple, EmergencyFlagUpdatedEvent.OutputTuple, EmergencyFlagUpdatedEvent.OutputObject>;
      EmergencyFlagUpdated: TypedContractEvent<EmergencyFlagUpdatedEvent.InputTuple, EmergencyFlagUpdatedEvent.OutputTuple, EmergencyFlagUpdatedEvent.OutputObject>;
    

      'RecordAdded(uint256,address,string,uint8,uint256)': TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
      RecordAdded: TypedContractEvent<RecordAddedEvent.InputTuple, RecordAddedEvent.OutputTuple, RecordAddedEvent.OutputObject>;
    

      'RecordArchived(uint256,address,uint256)': TypedContractEvent<RecordArchivedEvent.InputTuple, RecordArchivedEvent.OutputTuple, RecordArchivedEvent.OutputObject>;
      RecordArchived: TypedContractEvent<RecordArchivedEvent.InputTuple, RecordArchivedEvent.OutputTuple, RecordArchivedEvent.OutputObject>;
    

      'RecordDeleted(uint256,address,uint256)': TypedContractEvent<RecordDeletedEvent.InputTuple, RecordDeletedEvent.OutputTuple, RecordDeletedEvent.OutputObject>;
      RecordDeleted: TypedContractEvent<RecordDeletedEvent.InputTuple, RecordDeletedEvent.OutputTuple, RecordDeletedEvent.OutputObject>;
    

      'RecordRestored(uint256,address,uint256)': TypedContractEvent<RecordRestoredEvent.InputTuple, RecordRestoredEvent.OutputTuple, RecordRestoredEvent.OutputObject>;
      RecordRestored: TypedContractEvent<RecordRestoredEvent.InputTuple, RecordRestoredEvent.OutputTuple, RecordRestoredEvent.OutputObject>;
    
    };
  }