/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IUserRegistry {
      
    export type DoctorProfileStruct = {name: string, licenseNumber: string, specialty: string, institution: string, status: BigNumberish, verifiedAt: BigNumberish}

    export type DoctorProfileStructOutput = [name: string, licenseNumber: string, specialty: string, institution: string, status: bigint, verifiedAt: bigint] & {name: string, licenseNumber: string, specialty: string, institution: string, status: bigint, verifiedAt: bigint }
  

    export type UserProfileStruct = {role: BigNumberish, isRegistered: boolean, encryptionPublicKey: BytesLike, registeredAt: BigNumberish}

    export type UserProfileStructOutput = [role: bigint, isRegistered: boolean, encryptionPublicKey: string, registeredAt: bigint] & {role: bigint, isRegistered: boolean, encryptionPublicKey: string, registeredAt: bigint }
  
    }

  export interface IUserRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getDoctorProfile" | "getPendingDoctors" | "getPublicKey" | "getUserProfile" | "getUserRole" | "isDoctorVerified" | "isRegistered" | "registerAsDoctor" | "registerAsPatient" | "rejectDoctor" | "updatePublicKey" | "verifyDoctor"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DoctorRegistrationRequested" | "DoctorRejected" | "DoctorVerified" | "PublicKeyUpdated" | "UserRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'getDoctorProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPendingDoctors', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPublicKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isDoctorVerified', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registerAsDoctor', values: [string, string, string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'registerAsPatient', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'rejectDoctor', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'updatePublicKey', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyDoctor', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getDoctorProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingDoctors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDoctorVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAsDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAsPatient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectDoctor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyDoctor', data: BytesLike): Result;
  }

  
    export namespace DoctorRegistrationRequestedEvent {
      export type InputTuple = [doctorAddress: AddressLike, name: string, licenseNumber: string, timestamp: BigNumberish];
      export type OutputTuple = [doctorAddress: string, name: string, licenseNumber: string, timestamp: bigint];
      export interface OutputObject {doctorAddress: string, name: string, licenseNumber: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DoctorRejectedEvent {
      export type InputTuple = [doctorAddress: AddressLike, rejectedBy: AddressLike, reason: string, timestamp: BigNumberish];
      export type OutputTuple = [doctorAddress: string, rejectedBy: string, reason: string, timestamp: bigint];
      export interface OutputObject {doctorAddress: string, rejectedBy: string, reason: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DoctorVerifiedEvent {
      export type InputTuple = [doctorAddress: AddressLike, verifiedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [doctorAddress: string, verifiedBy: string, timestamp: bigint];
      export interface OutputObject {doctorAddress: string, verifiedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PublicKeyUpdatedEvent {
      export type InputTuple = [userAddress: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [userAddress: string, timestamp: bigint];
      export interface OutputObject {userAddress: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserRegisteredEvent {
      export type InputTuple = [userAddress: AddressLike, role: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [userAddress: string, role: bigint, timestamp: bigint];
      export interface OutputObject {userAddress: string, role: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IUserRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IUserRegistry;
    waitForDeployment(): Promise<this>;

    interface: IUserRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getDoctorProfile: TypedContractMethod<
      [_doctor: AddressLike, ],
      [IUserRegistry.DoctorProfileStructOutput],
      'view'
    >
    

    
    getPendingDoctors: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getPublicKey: TypedContractMethod<
      [_user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getUserProfile: TypedContractMethod<
      [_user: AddressLike, ],
      [IUserRegistry.UserProfileStructOutput],
      'view'
    >
    

    
    getUserRole: TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isDoctorVerified: TypedContractMethod<
      [_doctor: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [_user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    registerAsDoctor: TypedContractMethod<
      [_name: string, _licenseNumber: string, _specialty: string, _institution: string, _encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerAsPatient: TypedContractMethod<
      [_encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    rejectDoctor: TypedContractMethod<
      [_doctorAddress: AddressLike, _reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    updatePublicKey: TypedContractMethod<
      [_newPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyDoctor: TypedContractMethod<
      [_doctorAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getDoctorProfile'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [IUserRegistry.DoctorProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingDoctors'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPublicKey'): TypedContractMethod<
      [_user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getUserProfile'): TypedContractMethod<
      [_user: AddressLike, ],
      [IUserRegistry.UserProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getUserRole'): TypedContractMethod<
      [_user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isDoctorVerified'): TypedContractMethod<
      [_doctor: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [_user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerAsDoctor'): TypedContractMethod<
      [_name: string, _licenseNumber: string, _specialty: string, _institution: string, _encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerAsPatient'): TypedContractMethod<
      [_encryptionPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectDoctor'): TypedContractMethod<
      [_doctorAddress: AddressLike, _reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePublicKey'): TypedContractMethod<
      [_newPublicKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyDoctor'): TypedContractMethod<
      [_doctorAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DoctorRegistrationRequested'): TypedContractEvent<DoctorRegistrationRequestedEvent.InputTuple, DoctorRegistrationRequestedEvent.OutputTuple, DoctorRegistrationRequestedEvent.OutputObject>;
getEvent(key: 'DoctorRejected'): TypedContractEvent<DoctorRejectedEvent.InputTuple, DoctorRejectedEvent.OutputTuple, DoctorRejectedEvent.OutputObject>;
getEvent(key: 'DoctorVerified'): TypedContractEvent<DoctorVerifiedEvent.InputTuple, DoctorVerifiedEvent.OutputTuple, DoctorVerifiedEvent.OutputObject>;
getEvent(key: 'PublicKeyUpdated'): TypedContractEvent<PublicKeyUpdatedEvent.InputTuple, PublicKeyUpdatedEvent.OutputTuple, PublicKeyUpdatedEvent.OutputObject>;
getEvent(key: 'UserRegistered'): TypedContractEvent<UserRegisteredEvent.InputTuple, UserRegisteredEvent.OutputTuple, UserRegisteredEvent.OutputObject>;

    filters: {
      
      'DoctorRegistrationRequested(address,string,string,uint256)': TypedContractEvent<DoctorRegistrationRequestedEvent.InputTuple, DoctorRegistrationRequestedEvent.OutputTuple, DoctorRegistrationRequestedEvent.OutputObject>;
      DoctorRegistrationRequested: TypedContractEvent<DoctorRegistrationRequestedEvent.InputTuple, DoctorRegistrationRequestedEvent.OutputTuple, DoctorRegistrationRequestedEvent.OutputObject>;
    

      'DoctorRejected(address,address,string,uint256)': TypedContractEvent<DoctorRejectedEvent.InputTuple, DoctorRejectedEvent.OutputTuple, DoctorRejectedEvent.OutputObject>;
      DoctorRejected: TypedContractEvent<DoctorRejectedEvent.InputTuple, DoctorRejectedEvent.OutputTuple, DoctorRejectedEvent.OutputObject>;
    

      'DoctorVerified(address,address,uint256)': TypedContractEvent<DoctorVerifiedEvent.InputTuple, DoctorVerifiedEvent.OutputTuple, DoctorVerifiedEvent.OutputObject>;
      DoctorVerified: TypedContractEvent<DoctorVerifiedEvent.InputTuple, DoctorVerifiedEvent.OutputTuple, DoctorVerifiedEvent.OutputObject>;
    

      'PublicKeyUpdated(address,uint256)': TypedContractEvent<PublicKeyUpdatedEvent.InputTuple, PublicKeyUpdatedEvent.OutputTuple, PublicKeyUpdatedEvent.OutputObject>;
      PublicKeyUpdated: TypedContractEvent<PublicKeyUpdatedEvent.InputTuple, PublicKeyUpdatedEvent.OutputTuple, PublicKeyUpdatedEvent.OutputObject>;
    

      'UserRegistered(address,uint8,uint256)': TypedContractEvent<UserRegisteredEvent.InputTuple, UserRegisteredEvent.OutputTuple, UserRegisteredEvent.OutputObject>;
      UserRegistered: TypedContractEvent<UserRegisteredEvent.InputTuple, UserRegisteredEvent.OutputTuple, UserRegisteredEvent.OutputObject>;
    
    };
  }